### ISSUE TITLE
Extra action button last boss WM

### ISSUE THREAD

**Issue by Addonman** [brittyazel/Neuron#277]
I was doing M+ and lately every time i go there when i pick i think Alchoholic fire i cant throw it on adds (if you know that fight) since extra action button is not reacting.

**Comment by brittyazel** [comment]
Was this with MASTER or the version on Curse? I thought I had this fixed in MASTER, I just hadn't pushed a new release yet

**Comment by Addonman** [comment]
TBH not sure because i know i noticed it few weeks ago ,but since  there was fix in Master for Fishing buddy i used it. And after that  i am not sure if i did dungeon  before or after i used Master

**Comment by Addonman** [comment]
Did another dungeon and is still not working and this one was with Master

**Comment by brittyazel** [comment]
Can you try with the latest commit I put in master? I'm just taking a shot in the dark on this one, but it might fix it

**Comment by Addonman** [comment]
Finaly had chance to do it and  i think it fixed it

**Comment by brittyazel** [comment]
Awesome! It seems fixed for me as well
