### ISSUE TITLE
Bars don't stay in drag mode consistently when dragging abilities from the spell book or between buttons

### ISSUE THREAD

**Issue by raysmith59** [brittyazel/Neuron#287]
Been meaning to report this for a while, I'm having all kinds of issues when dragging spells from my spellbook to the action bars, as soon as I start the drag the bars go into "edit mode" (I can see the grid, it's disabled otherwise) but at least half the time if not more by the time I get the button there the bars are no longer in that mode.  I have this happen occasionally when moving or swapping buttons, too, but due to the shorter distance it's less likely to happen.

Should be easy enough to duplicate.  Disable grid, open spellbook, drag a spell out into the main play area and just leave it there for a few seconds and the bars should go out of edit mode.  Generally happens in 2 or 3 seconds for me, sometimes faster.

**Comment by raysmith59** [comment]
I'm probably the last to think of this but enabling the grid temporarily works around this.  Also means that the issue is likely with the grid being disabled, something is causing the grid to revert to hidden while the drag is still happening.  I took a bit of a look at the code but didn't see anything useful.

**Comment by brittyazel** [comment]
I'll look at it. It's probably something stupid that I overlooked, not to worry. I've been on a role reworking large swaths of code, so it makes sense that little things like this slip through. Thanks for being so diligent with the bug reports :-)

**Comment by brittyazel** [comment]
This is fixed as of today

**Comment by raysmith59** [comment]
I was just checking through the status of issues that are still occurring and noticed that this had been closed, it's still happening.
