### ISSUE TITLE
Issue: Extra action bar

### ISSUE THREAD

**Issue by SirLagardere** [brittyazel/Neuron#5]
When I get into a zone (or expedition) with an extra action button, the selected spell don't disapear even if I leave the zone or complete the expedition.
If I enter another zone or expedition needing the extra action, It's not refresh either.
No error logged
Seems to get the same behavior with the Zone Action Bar (If I go to my Garrison and tp back to Dalaran, I'll keep the spell on)

**Comment by brittyazel** [comment]
I can fix this! I think I know the change I made that borked this functionality, look for a fix to this pushed out tonight

**Comment by SirLagardere** [comment]
Wow thanks for the quick reply :) I'll test it asap

**Comment by brittyazel** [comment]
I'm pretty sure I fixed it. Please test it for me once I push the new release.

To clarify, your saying the "extra" action button won't go away, not the zone action button? The extra action button is the one that is used for quest items, exiting a taxi, etc. The zone button is the garrison ability and some bodyguard abilities

**Comment by SirLagardere** [comment]
Yes, the extra action button  persist even after leaving a zone where it was used.
The zone action button appears when needed but persist too. (i.e. Garrison button still present in Dalaran after port from there)

**Comment by brittyazel** [comment]
This is very strange behavior. I fixed the zone ability bar bug sticking around, but I can't replicate the extra action bar bug. Is there a place that this happens 100% of the time that I can test? Also do you have *show grid* enabled on that bar?

**Comment by SirLagardere** [comment]
Maybe it's me that wrongly configure the button.
My first goal was that the button appears only when needed, but never succed to do so...
So I let everything "on" (default creation)
![image](https://user-images.githubusercontent.com/20615278/31517349-edbe9d36-af9b-11e7-8ccc-e9a9e248c920.png)
And here, I'm outside of Suramar, but the "disguised" spell is still there
![image](https://user-images.githubusercontent.com/20615278/31517422-29376cda-af9c-11e7-84bd-7406bd2ff03b.png)
The only action that "reset" correctly is the "leave the mount" arrow (from a taxi or a vehicle for exemple)
Porting reset the spell too.

By the way, the zone action button is fixed on the 0.9.5a (just to confirm ^^)

**Comment by brittyazel** [comment]
Ok cool, I'm happy the Zone action button is fixed at least!

That's smart to use Suramar as the testing ground for the extra button, I'll go there once I'm off work and see what is happening.

One thing of note, are you using a non-english client? Perhaps French? I don't know if that would be a cause of some of your issues, but maybe something is hardcoded somewhere in English that I haven't come across yet.

**Comment by brittyazel** [comment]
Ok I just checked, and I absolutely can't replicate this. The second I enter suramar I get the prompt to put on a disguise, and the second I leave the button dissapears.

Maybe you can try deleting the extra bar and remaking it?

**Comment by SirLagardere** [comment]
Yep, French client here.
Try to delete the extra bar, and remake it, no go, still the same trouble.
Even try to switch to english, no luck too.
From your last post, I understand that the button only show up when you enter Suramar ? Have you change something on the bar visibility ? Here, I let evrything state on, and the bar is always on, maybe the trick is here ?

**Comment by brittyazel** [comment]
I haven't changed anything as far as bar visibility. My exta and zone bars are just set to the defaults.

Can you disable all other add-ons besides the neuron ones to see of maybe a different addon is causing the issue. 

No matter what I do I can get my bars to break in the same way yours are

**Comment by SirLagardere** [comment]
Very strange, just disable evrything else, and still get the same behavior...
It's like the update event was not intercept (pure speculation)...

**Comment by brittyazel** [comment]
Well it doesn't so much matter anymore, an angry maintainer over on the Ion project for which our project was forked decided to report the project and have it taken down. Looks like Neuron is down for the count for the time being.

**Comment by brittyazel** [comment]
The more I look into this the more confused I get. On a fresh profile do you get this behavior? I just want to rule it out as a setting that is somehow enabled, or if there is some client bug causing this. It's super annoying to not be able to replicate this issue.

**Comment by SirLagardere** [comment]
Ok, never thought it was a "profile" thingy, but, you narrowed it down. With a fresh profile no trouble at all.
And because of that, I remembered something. From my fresh install, I deleted everything, and then recreate only what I needed. Maybe there something different between the creation and store profile from a "first run" and from a recreation.
I'll test my other problem (issue #6) with the fresh profile, but I think it will be "corrected" too.
Thanks for your help, I'll continue my testing and report back for both of them here.

**Comment by brittyazel** [comment]
Excellent! that's odd, I'll check into the "initial creation" vs a manual creating for the extra bar to see if there's something different

**Comment by SirLagardere** [comment]
So, just to confirm, fresh profile is a go. No problem at all for the extra.
Thanks again for your time :)

**Comment by brittyazel** [comment]
I fixed this officially. You weren't crazy. When you created a new extra action bar from scratch it didn't get the right default visibility options. I fixed the defaults and made it so that this shouldn't happen again. The pet bar was also doing the exact same thing, so thanks for clueing me onto this bug lol.
